<?php

namespace AppBundle\Entity;

/**
 * ConseilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConseilRepository extends \Doctrine\ORM\EntityRepository
{
}
