version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    depends_on:
      - database
    environment:
      - PHPOOP_DB_HOST=database
      - PHPOOP_DB_NAME=paul
      - PHPOOP_DB_USER=paul
      - PHPOOP_DB_PASS=paul
      - PHPOOP_DB_PORT=3306
  database:
    image: mysql:5.7
    expose:
      - "3306"
    volumes:
      - ./fixtures/:/docker-entrypoint-initdb.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
