<?php

namespace AppBundle\Entity;

/**
 * DegreConseilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DegreConseilRepository extends \Doctrine\ORM\EntityRepository
{
}
