<?php

namespace AppBundle\Entity;

/**
 * TypeConseilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeConseilRepository extends \Doctrine\ORM\EntityRepository
{
}
